name: Run Alpha Tested Slack Notification

on:
  schedule:
    - cron: '30 1 * * 1-5'

jobs:
  cron:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r alpha-tested-notification/requirements.txt
    - name: Run
      env:
        JIRA_URL: ${{ secrets.JIRA_URL }}
        JIRA_USER_NAME: ${{ secrets.JIRA_USER_NAME }}
        JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
        SLACK_HOOK_URL: ${{ secrets.SLACK_HOOK_URL }}
      run: |
        python alpha-tested-notification/run.py
